version: '3'

services:
    cadvisor:
      image: google/cadvisor
      ports:
        - 7777:8080
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      
