version: "3"

services:
  wordpress:
    image: wordpress:4
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_PASSWORD=1234
    links:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - /root/com/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
